// frontend/src/components/ExportReports.js
import React, { useState } from 'react';
import {
  Box,
  Typography,
  Paper,
  Button,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  TextField,
  RadioGroup,
  FormControlLabel,
  Radio,
  Alert,
  CircularProgress,
  Grid
} from '@mui/material';
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import InsertChartIcon from '@mui/icons-material/InsertChart';
import DownloadIcon from '@mui/icons-material/Download';
import EmailIcon from '@mui/icons-material/Email';

const ExportReports = ({ backendUrl, analysisResult, statistics }) => {
  const [exportFormat, setExportFormat] = useState('pdf');
  const [timeRange, setTimeRange] = useState('all');
  const [includeCharts, setIncludeCharts] = useState(true);
  const [email, setEmail] = useState('');
  const [exporting, setExporting] = useState(false);
  const [exportSuccess, setExportSuccess] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    
    // Simulate export process (in real app, this would call your backend)
    setTimeout(() => {
      setExporting(false);
      setExportSuccess(true);
      
      // Reset success message after 5 seconds
      setTimeout(() => setExportSuccess(false), 5000);
      
      // Generate and download a mock file
      if (exportFormat === 'csv') {
        downloadCSV();
      } else {
        downloadPDF();
      }
    }, 2000);
  };

  const downloadCSV = () => {
    const csvContent = "data:text/csv;charset=utf-8," 
      + "Date,Clarity Score,Confidence Score,Filler Words,Word Count\n"
      + "2024-01-15,8.2,7.5,3,145\n"
      + "2024-01-16,8.5,7.8,2,167\n"
      + "2024-01-17,8.7,8.1,1,189\n"
      + "2024-01-18,9.0,8.4,0,203";
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "vocalcoach-progress-report.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const downloadPDF = () => {
    // In real implementation, this would generate a PDF
    alert('PDF export would be generated by the backend. For demo, CSV is downloaded.');
    downloadCSV(); // Fallback to CSV for demo
  };

  const sendEmailReport = () => {
    if (!email) {
      alert('Please enter your email address');
      return;
    }
    
    alert(`Report would be sent to ${email}. In production, this would call your backend email service.`);
  };

  return (
    <Paper elevation={2} sx={{ p: 3, borderRadius: 2, mb: 3 }}>
      <Typography variant="h6" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        📤 Export Progress Reports
      </Typography>
      
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        Export your progress data, analysis results, and statistics for sharing or record-keeping.
      </Typography>
      
      <Grid container spacing={3}>
        <Grid item xs={12} md={6}>
          <FormControl fullWidth size="small" sx={{ mb: 2 }}>
            <InputLabel>Export Format</InputLabel>
            <Select
              value={exportFormat}
              label="Export Format"
              onChange={(e) => setExportFormat(e.target.value)}
            >
              <MenuItem value="pdf">
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  <PictureAsPdfIcon fontSize="small" />
                  PDF Document
                </Box>
              </MenuItem>
              <MenuItem value="csv">
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  <InsertChartIcon fontSize="small" />
                  CSV Spreadsheet
                </Box>
              </MenuItem>
            </Select>
          </FormControl>
          
          <FormControl fullWidth size="small" sx={{ mb: 2 }}>
            <InputLabel>Time Range</InputLabel>
            <Select
              value={timeRange}
              label="Time Range"
              onChange={(e) => setTimeRange(e.target.value)}
            >
              <MenuItem value="7days">Last 7 Days</MenuItem>
              <MenuItem value="30days">Last 30 Days</MenuItem>
              <MenuItem value="all">All Time</MenuItem>
            </Select>
          </FormControl>
          
          <FormControl component="fieldset" sx={{ mb: 2 }}>
            <Typography variant="body2" gutterBottom>
              Include Charts & Visualizations
            </Typography>
            <RadioGroup
              row
              value={includeCharts}
              onChange={(e) => setIncludeCharts(e.target.value === 'true')}
            >
              <FormControlLabel value={true} control={<Radio size="small" />} label="Yes" />
              <FormControlLabel value={false} control={<Radio size="small" />} label="No" />
            </RadioGroup>
          </FormControl>
        </Grid>
        
        <Grid item xs={12} md={6}>
          <Typography variant="body2" gutterBottom>
            Email Report (Optional)
          </Typography>
          <Box sx={{ display: 'flex', gap: 1, mb: 3 }}>
            <TextField
              fullWidth
              size="small"
              placeholder="your.email@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <Button
              variant="outlined"
              startIcon={<EmailIcon />}
              onClick={sendEmailReport}
              disabled={!email}
            >
              Send
            </Button>
          </Box>
          
          {exportSuccess && (
            <Alert severity="success" sx={{ mb: 2 }}>
              Report exported successfully! Check your downloads.
            </Alert>
          )}
          
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
            <Button
              variant="contained"
              startIcon={exporting ? <CircularProgress size={20} color="inherit" /> : <DownloadIcon />}
              onClick={handleExport}
              disabled={exporting}
              sx={{ flexGrow: 1 }}
            >
              {exporting ? 'Exporting...' : 'Export Report'}
            </Button>
            
            <Button
              variant="outlined"
              onClick={() => window.print()}
            >
              Print Summary
            </Button>
          </Box>
        </Grid>
      </Grid>
      
      <Box sx={{ mt: 3, pt: 2, borderTop: '1px solid #374151' }}>
        <Typography variant="caption" color="text.secondary">
          Exports include: Session history, progress charts, analysis scores, and improvement recommendations.
        </Typography>
      </Box>
    </Paper>
  );
};

export default ExportReports;